### ISSUE TITLE
IOS streaming

### ISSUE THREAD

**Issue by Aathi** [EstebanFuentealba/react-native-android-audio-streaming-aac#2]
### plugin

https://github.com/leblaaanc/react-native-streamingkit
### issue

https://github.com/LeBlaaanc/react-native-streamingkit/issues/1
### fix

https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking
### sample app

https://github.com/Aathi/react-native-streamingkit-sample-app

**Comment by tlenclos** [comment]
Hi there, I created a merge of this module and streaming kit, with media center control and notifications.

https://github.com/tlenclos/react-native-audio-streaming

**Comment by Aathi** [comment]
@tlenclos really nice piece of work 💃
